# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://zhanghaiyang.org
date_format: "ordinal"
title: 养码场
subtitle: "屌丝程序员的成长之路"
description: "张海洋的个人博客"
keywords: 养码场, Zhang Haiyang, haiyangzhang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Haiyang Zhang
organization: jd.com
organization_url: http://www.jd.com
github_username: pzhaiyang
location: NanJing, China
email: 18761600650@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: pzhaiyang/pzhaiyang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: pzhaiyang
# https://gentie.163.com
netease_gentie:
    productKey: 560ed243b708465d82d5a0a5f3b83da1
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: pzhaiyang
    repo: blog-comments
    oauth:
        client_id: 1ccf0192c22afe6627b3
        client_secret: baa81e33de39241c7ee45a587058613209b61a68
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
